CREATE TABLE IF NOT EXISTS "migrations" ("id" integer not null primary key autoincrement, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "users" ("id" integer not null primary key autoincrement, "email" varchar, "email_verified_at" datetime, "password" varchar, "first_name" varchar not null, "last_name" varchar not null, "username" varchar, "identity_number" varchar, "phone" varchar, "gender" varchar, "birth_date" date, "birth_place" varchar, "personal_image" varchar, "father_name" varchar, "mother_name" varchar, "status" varchar, "qr_code" varchar, "blood_type" varchar, "note" text, "current_address" varchar, "is_has_disease" varchar, "disease_name" varchar, "is_has_treatment" varchar, "treatment_name" varchar, "are_there_disease_in_family" varchar, "family_disease_note" varchar, "property_id" integer, "image" varchar, "is_approved" varchar default 'false', "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("property_id") references "properties"("id"));
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE UNIQUE INDEX "users_username_unique" on "users" ("username");
CREATE UNIQUE INDEX "users_identity_number_unique" on "users" ("identity_number");
CREATE UNIQUE INDEX "users_qr_code_unique" on "users" ("qr_code");
CREATE TABLE IF NOT EXISTS "password_resets" ("email" varchar not null, "token" varchar not null, "created_at" datetime);
CREATE INDEX "password_resets_email_index" on "password_resets" ("email");
CREATE TABLE IF NOT EXISTS "telescope_entries" ("sequence" integer not null primary key autoincrement, "uuid" varchar not null, "batch_id" varchar not null, "family_hash" varchar, "should_display_on_index" tinyint(1) not null default '1', "type" varchar not null, "content" text not null, "created_at" datetime);
CREATE UNIQUE INDEX "telescope_entries_uuid_unique" on "telescope_entries" ("uuid");
CREATE INDEX "telescope_entries_batch_id_index" on "telescope_entries" ("batch_id");
CREATE INDEX "telescope_entries_family_hash_index" on "telescope_entries" ("family_hash");
CREATE INDEX "telescope_entries_created_at_index" on "telescope_entries" ("created_at");
CREATE INDEX "telescope_entries_type_should_display_on_index_index" on "telescope_entries" ("type", "should_display_on_index");
CREATE TABLE IF NOT EXISTS "telescope_entries_tags" ("entry_uuid" varchar not null, "tag" varchar not null, foreign key("entry_uuid") references "telescope_entries"("uuid") on delete cascade);
CREATE INDEX "telescope_entries_tags_entry_uuid_tag_index" on "telescope_entries_tags" ("entry_uuid", "tag");
CREATE INDEX "telescope_entries_tags_tag_index" on "telescope_entries_tags" ("tag");
CREATE TABLE IF NOT EXISTS "telescope_monitoring" ("tag" varchar not null);
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer not null primary key autoincrement, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime default CURRENT_TIMESTAMP not null);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer not null primary key autoincrement, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "organizations" ("id" integer not null primary key autoincrement, "name" varchar not null, "logo" varchar, "location" varchar, "capacity" varchar, "website" varchar, "description" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE TABLE IF NOT EXISTS "branches" ("id" integer not null primary key autoincrement, "name" varchar not null, "organization_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("organization_id") references "organizations"("id") on delete cascade on update cascade);
CREATE TABLE IF NOT EXISTS "properties" ("id" integer not null primary key autoincrement, "name" varchar not null, "capacity" varchar not null, "property_type" varchar not null, "description" text, "email" varchar, "phone" varchar, "whatsapp" varchar, "facebook" varchar, "instagram" varchar, "location" text, "image" varchar, "branch_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("branch_id") references "branches"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "grades" ("id" integer not null primary key autoincrement, "name" varchar not null, "description" text, "property_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("property_id") references "properties"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "class_rooms" ("id" integer not null primary key autoincrement, "grade_id" integer not null, "name" varchar, "description" text, "capacity" varchar, "image" varchar, "is_approved" varchar default 'false', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("grade_id") references "grades"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "admins" ("id" integer not null primary key autoincrement, "user_id" integer not null, "job_title_id" integer, "marital_status" varchar default '0', "wives_count" varchar, "children_count" varchar, "property_id" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("user_id") references "users"("id"), foreign key("job_title_id") references "job_titles"("id"), foreign key("property_id") references "properties"("id"));
CREATE TABLE IF NOT EXISTS "students" ("id" integer not null primary key autoincrement, "user_id" integer not null, "parent_work" varchar, "family_members_count" varchar, "is_orphan" varchar default '0', "parent_phone" varchar, "who_is_parent" varchar, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "teachers" ("id" integer not null primary key autoincrement, "user_id" integer not null, "marital_status" varchar default '0', "wives_count" varchar, "children_count" varchar, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "subjects" ("id" integer not null primary key autoincrement, "name" varchar not null, "description" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE TABLE IF NOT EXISTS "books" ("id" integer not null primary key autoincrement, "name" varchar not null, "property_type" varchar not null, "book_type" varchar not null, "size" varchar, "paper_count" varchar, "author_name" varchar, "image" varchar, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE UNIQUE INDEX "books_name_unique" on "books" ("name");
CREATE TABLE IF NOT EXISTS "subject_books" ("id" integer not null primary key autoincrement, "book_id" integer not null, "subject_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("book_id") references "books"("id"), foreign key("subject_id") references "subjects"("id"));
CREATE TABLE IF NOT EXISTS "certifications" ("id" integer not null primary key autoincrement, "user_id" integer not null, "certificate_type" varchar, "image" varchar, "issuing_date" varchar, "expiration_date" varchar, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" integer not null primary key autoincrement, "class_room_id" integer not null, "teacher_id" integer not null, "name" varchar, "subject_name" varchar, "description" text, "date" varchar, "start_at" datetime, "duration" varchar, "place" varchar, "type" varchar, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("class_room_id") references "class_rooms"("id"), foreign key("teacher_id") references "teachers"("id"));
CREATE TABLE IF NOT EXISTS "activity_types" ("id" integer not null primary key autoincrement, "name" varchar not null, "description" text, "goal" varchar, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE TABLE IF NOT EXISTS "activities" ("id" integer not null primary key autoincrement, "class_room_id" integer not null, "activity_type_id" integer not null, "teacher_id" integer not null, "name" varchar, "place" varchar, "cost" varchar, "result" varchar, "note" text, "start_datetime" datetime, "end_datetime" datetime, "image" varchar, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("class_room_id") references "class_rooms"("id"), foreign key("activity_type_id") references "activity_types"("id"), foreign key("teacher_id") references "teachers"("id"));
CREATE TABLE IF NOT EXISTS "schools" ("id" integer not null primary key autoincrement, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE TABLE IF NOT EXISTS "mosques" ("id" integer not null primary key autoincrement, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE TABLE IF NOT EXISTS "rates" ("id" integer not null primary key autoincrement, "teacher_id" integer not null, "admin_id" integer, "date" varchar, "start_date" varchar, "end_date" varchar, "correct_reading_skill" varchar, "teaching_skill" varchar, "academic_skill" varchar, "following_skill" varchar, "plan_commitment" varchar, "time_commitment" varchar, "student_commitment" varchar, "activity" varchar, "commitment_to_administrative_instructions" varchar, "exam_and_quizzes" varchar, "score" varchar, "percentage" varchar, "note" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("teacher_id") references "teachers"("id"), foreign key("admin_id") references "admins"("id"));
CREATE TABLE IF NOT EXISTS "class_room_teachers" ("id" integer not null primary key autoincrement, "class_room_id" integer not null, "teacher_id" integer not null, "joined_at" date not null, "left_at" date, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("class_room_id") references "class_rooms"("id"), foreign key("teacher_id") references "teachers"("id"));
CREATE TABLE IF NOT EXISTS "class_room_students" ("id" integer not null primary key autoincrement, "class_room_id" integer not null, "student_id" integer not null, "joined_at" date not null, "left_at" date, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("class_room_id") references "class_rooms"("id"), foreign key("student_id") references "students"("id"));
CREATE TABLE IF NOT EXISTS "organization_admins" ("id" integer not null primary key autoincrement, "organization_id" integer not null, "admin_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("organization_id") references "organizations"("id"), foreign key("admin_id") references "admins"("id"));
CREATE TABLE IF NOT EXISTS "branch_admins" ("id" integer not null primary key autoincrement, "branch_id" integer not null, "admin_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("branch_id") references "branches"("id"), foreign key("admin_id") references "admins"("id"));
CREATE TABLE IF NOT EXISTS "property_admins" ("id" integer not null primary key autoincrement, "property_id" integer not null, "admin_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("property_id") references "properties"("id") on delete cascade, foreign key("admin_id") references "admins"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "session_attendances" ("id" integer not null primary key autoincrement, "session_id" integer not null, "student_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("session_id") references "sessions"("id"), foreign key("student_id") references "students"("id"));
CREATE TABLE IF NOT EXISTS "participants" ("id" integer not null primary key autoincrement, "activity_id" integer not null, "student_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("activity_id") references "activities"("id"), foreign key("student_id") references "students"("id"));
CREATE TABLE IF NOT EXISTS "note_types" ("id" integer not null primary key autoincrement, "name" varchar not null, "description" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "notes" ("id" integer not null primary key autoincrement, "student_id" integer not null, "teacher_id" integer, "admin_id" integer, "date" varchar not null, "teacher_content" text, "admin_content" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("student_id") references "students"("id"), foreign key("teacher_id") references "teachers"("id"), foreign key("admin_id") references "admins"("id"));
CREATE TABLE IF NOT EXISTS "calendars" ("id" integer not null primary key autoincrement, "class_room_id" integer not null, "day_name" varchar not null, "subject_name" varchar, "start_at" varchar not null, "end_at" varchar not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("class_room_id") references "class_rooms"("id"));
CREATE TABLE IF NOT EXISTS "interviews" ("id" integer not null primary key autoincrement, "name" varchar not null, "event_place" varchar, "date" varchar, "goal" varchar, "comment" text, "type" varchar, "image" varchar, "score" varchar, "student_id" integer not null, "teacher_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("student_id") references "students"("id"), foreign key("teacher_id") references "teachers"("id"));
CREATE TABLE IF NOT EXISTS "quran_quizzes" ("id" integer not null primary key autoincrement, "name" varchar not null, "juz" varchar not null, "page" varchar not null, "date" varchar not null, "exam_type" varchar not null, "score" varchar not null, "student_id" integer not null, "teacher_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("student_id") references "students"("id"), foreign key("teacher_id") references "teachers"("id"));
CREATE TABLE IF NOT EXISTS "quizzes" ("id" integer not null primary key autoincrement, "name" varchar not null, "quiz_subject" varchar not null, "date" varchar not null, "time" varchar not null, "quiz_type" varchar not null, "score" varchar not null, "student_id" integer not null, "teacher_id" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("student_id") references "students"("id"), foreign key("teacher_id") references "teachers"("id"));
CREATE TABLE IF NOT EXISTS "book_class_room" ("id" integer not null primary key autoincrement, "book_id" integer not null, "class_room_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("book_id") references "books"("id") on delete cascade, foreign key("class_room_id") references "class_rooms"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "job_titles" ("id" integer not null primary key autoincrement, "name" varchar not null, "description" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2014_10_12_100000_create_password_resets_table',1);
INSERT INTO migrations VALUES(3,'2018_08_08_100000_create_telescope_entries_table',1);
INSERT INTO migrations VALUES(4,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(5,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(6,'2022_08_21_194120_create_organizations_table',1);
INSERT INTO migrations VALUES(7,'2022_08_22_194326_create_branches_table',1);
INSERT INTO migrations VALUES(8,'2022_08_23_203848_create_properties_table',1);
INSERT INTO migrations VALUES(9,'2022_08_24_202600_create_permission_tables',1);
INSERT INTO migrations VALUES(10,'2022_08_24_211203_create_grades_table',1);
INSERT INTO migrations VALUES(11,'2022_08_24_212013_create_class_rooms_table',1);
INSERT INTO migrations VALUES(12,'2022_08_24_212154_create_class_room_groups_table',1);
INSERT INTO migrations VALUES(13,'2022_08_24_213454_create_job_titles_table',1);
INSERT INTO migrations VALUES(14,'2022_08_24_215926_create_admins_table',1);
INSERT INTO migrations VALUES(15,'2022_08_24_220011_create_students_table',1);
INSERT INTO migrations VALUES(16,'2022_08_24_220033_create_user_parents_table',1);
INSERT INTO migrations VALUES(17,'2022_08_24_220047_create_teachers_table',1);
INSERT INTO migrations VALUES(18,'2022_08_27_214552_create_subjects_table',1);
INSERT INTO migrations VALUES(19,'2022_08_27_215257_create_books_table',1);
INSERT INTO migrations VALUES(20,'2022_08_27_220134_create_subject_books_table',1);
INSERT INTO migrations VALUES(21,'2022_08_29_184108_create_addresses_table',1);
INSERT INTO migrations VALUES(22,'2022_08_29_184524_create_contacts_table',1);
INSERT INTO migrations VALUES(23,'2022_08_30_152411_create_patients_table',1);
INSERT INTO migrations VALUES(24,'2022_08_31_194347_create_patient_treatments_table',1);
INSERT INTO migrations VALUES(25,'2022_08_31_231719_create_certificate_types_table',1);
INSERT INTO migrations VALUES(26,'2022_08_31_231720_create_certifications_table',1);
INSERT INTO migrations VALUES(27,'2022_09_01_213341_create_sessions_table',1);
INSERT INTO migrations VALUES(28,'2022_09_01_220721_create_attendances_table',1);
INSERT INTO migrations VALUES(29,'2022_09_01_221928_create_references_table',1);
INSERT INTO migrations VALUES(30,'2022_09_01_223830_create_scores_table',1);
INSERT INTO migrations VALUES(31,'2022_09_01_224442_create_activity_types_table',1);
INSERT INTO migrations VALUES(32,'2022_09_01_225717_create_activities_table',1);
INSERT INTO migrations VALUES(33,'2022_10_10_196030_create_status_types_table',1);
INSERT INTO migrations VALUES(34,'2022_10_11_190000_create_statuses_table',1);
INSERT INTO migrations VALUES(35,'2022_10_11_194026_create_model_statuses_table',1);
INSERT INTO migrations VALUES(36,'2022_10_11_212124_create_schools_table',1);
INSERT INTO migrations VALUES(37,'2022_10_11_212926_create_mosques_table',1);
INSERT INTO migrations VALUES(38,'2022_10_22_202512_create_certificate_details_table',1);
INSERT INTO migrations VALUES(39,'2022_10_22_202907_create_certificate_transcripts_table',1);
INSERT INTO migrations VALUES(40,'2022_10_23_222306_create_rate_types_table',1);
INSERT INTO migrations VALUES(41,'2022_10_24_221752_create_rates_table',1);
INSERT INTO migrations VALUES(42,'2022_10_25_234025_create_report_types_table',1);
INSERT INTO migrations VALUES(43,'2022_10_25_234205_create_reports_table',1);
INSERT INTO migrations VALUES(44,'2022_10_30_101842_create_class_room_teachers_table',1);
INSERT INTO migrations VALUES(45,'2022_10_30_105916_create_class_room_students_table',1);
INSERT INTO migrations VALUES(46,'2022_10_31_234033_create_report_contents_table',1);
INSERT INTO migrations VALUES(47,'2022_10_31_234143_create_report_reviewers_table',1);
INSERT INTO migrations VALUES(48,'2022_12_22_235405_create_organization_admins_table',1);
INSERT INTO migrations VALUES(49,'2022_12_22_235852_create_branch_admins_table',1);
INSERT INTO migrations VALUES(50,'2022_12_22_235853_create_property_admins_table',1);
INSERT INTO migrations VALUES(51,'2022_12_27_002029_create_session_attendances_table',1);
INSERT INTO migrations VALUES(52,'2022_12_27_002317_create_participants_table',1);
INSERT INTO migrations VALUES(53,'2022_12_30_172046_create_note_types_table',1);
INSERT INTO migrations VALUES(54,'2022_12_30_172107_create_notes_table',1);
INSERT INTO migrations VALUES(55,'2023_01_28_203019_create_calendars_table',1);
INSERT INTO migrations VALUES(56,'2023_01_29_193643_create_interviews_table',1);
INSERT INTO migrations VALUES(57,'2023_01_29_195349_create_quran_quizzes_table',1);
INSERT INTO migrations VALUES(58,'2023_02_04_120926_create_quizzes_table',1);
INSERT INTO migrations VALUES(59,'2023_03_26_085655_create_book_class_room_table',1);
INSERT INTO migrations VALUES(60,'2025_10_11_000000_create_job_titles_table',1);
